name: test_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  freezed_annotation: ^2.1.0 
  get_it: ^7.2.0
  google_sign_in: ^6.1.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  auth_buttons: ^3.0.0
  flutter_facebook_auth: ^5.0.8
  location: ^4.4.0
  flutter_map: ^3.1.0
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  freezed: ^2.0.4
  flutter_lints: ^2.0.0

  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
